-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-04-17 15:14:57 BRT
--   site:      SQL Server 2008
--   type:      SQL Server 2008




CREATE
  TABLE Beneficiario
  (
    IDBeneficiario INTEGER NOT NULL ,
    IDContrato     INTEGER NOT NULL ,
    IDCliente      INTEGER NOT NULL ,
    CONSTRAINT Beneficiario_PK PRIMARY KEY CLUSTERED (IDBeneficiario)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Cliente
  (
    IDCliente INTEGER NOT NULL ,
    Nome      VARCHAR (100) NOT NULL ,
    RG        VARCHAR (12) NOT NULL ,
    CPF       VARCHAR (12) NOT NULL ,
    Idade     INTEGER NOT NULL ,
    Telefone  VARCHAR (15) NOT NULL ,
    Email     VARCHAR (120) NOT NULL ,
    Endereco  VARCHAR (120) NOT NULL ,
    CEP       VARCHAR (8) NOT NULL ,
    Bairro    VARCHAR (100) NOT NULL ,
    Cidade    VARCHAR (100) NOT NULL ,
    CONSTRAINT Cliente_PK PRIMARY KEY CLUSTERED (IDCliente)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Contrato
  (
    IDContrato       INTEGER NOT NULL ,
    DataInicio       DATE NOT NULL ,
    DataFinal        DATE NOT NULL ,
    EnderecoEnvio    VARCHAR (120) NOT NULL ,
    CEPEnvio         VARCHAR (8) NOT NULL ,
    EnderecoCobranca VARCHAR (120) NOT NULL ,
    CEPCobranca      VARCHAR (8) NOT NULL ,
    IDCliente        INTEGER NOT NULL ,
    IDSeguro         INTEGER NOT NULL ,
    BairroEnvio      VARCHAR (120) NOT NULL ,
    CidadeEnvio      VARCHAR (120) NOT NULL ,
    BairroCobranca   VARCHAR (120) NOT NULL ,
    CidadeCobranca   VARCHAR (120) NOT NULL ,
    CONSTRAINT Contrato_PK PRIMARY KEY CLUSTERED (IDContrato)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Seguro
  (
    IDSeguro    INTEGER NOT NULL ,
    TipoSeguro  VARCHAR (50) NOT NULL ,
    ValorSeguro DECIMAL (12,2) NOT NULL ,
    CONSTRAINT Seguro_PK PRIMARY KEY CLUSTERED (IDSeguro)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

ALTER TABLE Beneficiario
ADD CONSTRAINT Beneficiario_Cliente_FK FOREIGN KEY
(
IDCliente
)
REFERENCES Cliente
(
IDCliente
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Beneficiario
ADD CONSTRAINT Beneficiario_Contrato_FK FOREIGN KEY
(
IDContrato
)
REFERENCES Contrato
(
IDContrato
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Contrato
ADD CONSTRAINT Contrato_Cliente_FK FOREIGN KEY
(
IDCliente
)
REFERENCES Cliente
(
IDCliente
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Contrato
ADD CONSTRAINT Contrato_Seguro_FK FOREIGN KEY
(
IDSeguro
)
REFERENCES Seguro
(
IDSeguro
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              4
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
