select * from LOGNAVEGACAO;

select * from ACAO;

select * from RELATORIO ORDER BY CODIGOANUNCIO, TO_CHAR(DATANAVEGACAO, 'dd/MM/yyyy'), ACAO;

DROP TABLE RELATORIO;

CREATE TABLE RELATORIO AS
SELECT CODIGOANUNCIO AS CODIGOANUNCIO,
      TRUNC(DATANAVEGACAO) AS DATANAVEGACAO,
      COUNT(1) AS TOTALACAO,
      TIPOACAO AS ACAO
FROM LOGNAVEGACAO
GROUP BY CODIGOANUNCIO, TRUNC(DATANAVEGACAO), TIPOACAO;

SELECT COUNT(1)
FROM LOGNAVEGACAO;

DESCRIBE LOGNAVEGACAOCONSOLIDADO;